<script lang="ts">
 import {untrack} from 'svelte';import Button from '../../design-system/components/Button.svelte';import FormField from '../../design-system/components/FormField.svelte';
 let{entity,initial={},onSave,onCancel}:{entity:'user'|'vaccine'|'batch'|'insurance';initial?:Record<string,string>;onSave:(values:Record<string,string>)=>void;onCancel:()=>void}=$props();
 const configs={
  user:{title:'Usuário',fields:[['name','Nome completo','text'],['email','E-mail','email'],['role','Perfil','select'],['status','Situação','status']]},
  vaccine:{title:'Vacina',fields:[['name','Nome da vacina','text'],['manufacturer','Fabricante','text'],['age','Indicação','text'],['price','Valor-base','text'],['status','Situação','status']]},
  batch:{title:'Lote',fields:[['number','Número do lote','text'],['vaccine','Vacina','text'],['manufacturer','Fabricante','text'],['expires','Validade','text'],['quantity','Quantidade','text'],['status','Situação','batchStatus']]},
  insurance:{title:'Convênio',fields:[['company','Convênio','text'],['plan','Plano','text'],['code','Código operacional','text'],['validUntil','Validade','text'],['status','Situação','status']]}
 } as const;
 let values=$state<Record<string,string>>(untrack(()=>({...initial})));let error=$state('');let config=$derived(configs[entity]);
 function submit(e:SubmitEvent){e.preventDefault();const required=config.fields.filter(f=>f[0]!=='status');if(required.some(f=>!values[f[0]]?.trim())){error='Preencha todos os campos obrigatórios.';return}onSave({...values})}
</script>
<div class="backdrop" role="presentation" onclick={(e)=>e.target===e.currentTarget&&onCancel()}><div role="dialog" aria-modal="true" aria-labelledby="crud-title"><form onsubmit={submit}><header><div><p>{Object.keys(initial).length?'Editar':'Cadastrar'}</p><h2 id="crud-title">{config.title}</h2></div><button type="button" aria-label="Fechar" onclick={onCancel}>×</button></header>{#if error}<div class="error" role="alert">{error}</div>{/if}<div class="fields">{#each config.fields as field}{#if field[2]==='select'}<label>{field[1]}<select value={values[field[0]]??'Paciente'} onchange={(e)=>values[field[0]]=e.currentTarget.value}><option>Paciente</option><option>Funcionário</option><option>Administrador</option></select></label>{:else if field[2]==='status'}<label>{field[1]}<select value={values[field[0]]??'Ativo'} onchange={(e)=>values[field[0]]=e.currentTarget.value}><option>Ativo</option><option>Inativo</option></select></label>{:else if field[2]==='batchStatus'}<label>{field[1]}<select value={values[field[0]]??'Regular'} onchange={(e)=>values[field[0]]=e.currentTarget.value}><option>Regular</option><option>Atenção</option><option>Crítico</option><option>Inativo</option></select></label>{:else}<FormField id={`crud-${field[0]}`} label={field[1]} type={field[2]==='email'?'email':'text'} value={values[field[0]]??''} oninput={(v)=>values[field[0]]=v} required/>{/if}{/each}</div><footer><Button variant="secondary" onclick={onCancel}>Cancelar</Button><Button type="submit">Salvar</Button></footer></form></div></div>
<style>.backdrop{position:fixed;z-index:90;inset:0;display:grid;place-items:center;background:var(--surface-overlay);padding:var(--space-5)}form{width:min(100%,38rem);max-height:calc(100vh - 2rem);overflow:auto;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface-card);padding:var(--space-6);box-shadow:var(--shadow-md)}header{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:var(--space-5)}header p{color:var(--color-brand-500);font-size:var(--text-xs);font-weight:800;text-transform:uppercase}h2{margin-top:.2rem;font-size:var(--text-xl)}header button{border:0;background:transparent;color:var(--text-secondary);font-size:1.5rem;cursor:pointer}.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:var(--space-4)}label{display:grid;gap:var(--space-2);color:var(--text-primary);font-size:var(--text-sm);font-weight:650}select{min-height:2.875rem;border:1px solid var(--border-strong);border-radius:var(--radius-md);background:var(--surface-card);padding:0 var(--space-3);color:var(--text-primary)}.error{margin-bottom:var(--space-4);border-radius:var(--radius-sm);background:var(--status-danger-bg);padding:var(--space-3);color:var(--status-danger);font-size:var(--text-sm)}footer{display:flex;justify-content:flex-end;gap:var(--space-3);margin-top:var(--space-6);border-top:1px solid var(--border-subtle);padding-top:var(--space-5)}@media(max-width:600px){.fields{grid-template-columns:1fr}}</style>
